/**
 * Domain model for an eBay product, composed with interface inheritance:
 *
 *   ProductInput  — the fields a client sends
 *   ProductMeta   — the fields the database generates on insert
 *   ProductRecord — a fully persisted row (input + metadata)
 */

/** The client-supplied fields of an eBay product. */
export interface ProductInput {
  title: string;
  price: number;
  item_id: string;
}

/** Fields generated by Supabase/PostgreSQL when a row is created. */
export interface ProductMeta {
  id: string;
  created_at: string;
}

/** A fully persisted product row = client input + database metadata. */
export interface ProductRecord extends ProductInput, ProductMeta {}
